[package]
name = "stm-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
minisign-verify.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tauri.workspace = true
tauri-plugin-single-instance.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-updater.workspace = true
time.workspace = true
stm-core = { path = "../crates/stm-core" }
stm-runtime = { path = "../crates/stm-runtime" }

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
