export const visibleCopyKeys = [
  "nav.dashboard",
  "nav.tools",
  "nav.skills",
  "nav.mcp",
  "nav.updates",
  "nav.history",
  "nav.settings",
  "scenario.label",
  "state.inventory.empty",
  "state.inventory.loading",
  "state.inventory.partial",
  "state.inventory.stale",
  "state.mapping.unsupported",
  "state.mapping.blocked",
  "state.manager.unavailable",
  "state.network.offline",
  "state.operation.cancelled",
  "state.operation.failed",
  "state.operation.recovery_available",
  "state.skill.local_modification",
  "state.skill.partial_failure",
  "state.product_update.recovery_available",
  "state.source.invalid",
  "state.source.review_required",
  "state.mcp.auth_reference_missing",
  "state.mcp.client_unsupported",
  "state.mcp.health_degraded",
] as const;

export type VisibleCopyKey = (typeof visibleCopyKeys)[number];
